In [31]:
import numpy as np
import math

In [73]:
# def inverse_glf_map(T):

#     f = np.zeros((4,1))
#     # print(f[0][0])

#     for i in range(np.shape(T)[1]):

#         if T[0][i] >= 250:
#             T[i] = 250
#         elif T[i] < -100:
#             T[i] = -100
#         if 0.06 <= T[i] < 1.2:
#             T[i] = 0.06
        
#         if T[i] >= 1.2:
#             A = 0.01
#             K = 59.82
#             B = 5.0
#             nu = 0.38
#             C = 0.56
#             M = 0.

#         if T[i] <= 0.06:
#             A = -199.13
#             K = -0.09
#             B = 8.84
#             nu = 5.34
#             C = 0.99
#             M = -0.57

#         f[i][0] = M - (1/B)*math.log((((K-A)/(T[i]-A))**nu)-C)
    
#     return f

def inverse_glf_map(T):
    if T >= 250:
        T = 250
    elif T < -100:
        T = -100
    if 0.06 <= T < 1.2:
        T = 0.06
    
    if T >= 1.2:
        A = 0.01
        K = 59.82
        B = 5.0
        nu = 0.38
        C = 0.56
        M = 0.

    if T <= 0.06:
        A = -199.13
        K = -0.09
        B = 8.84
        nu = 5.34
        C = 0.99
        M = -0.57
    cmd = M - (1/B)*math.log((((K-A)/(T-A))**nu)-C)
    return cmd

In [74]:
lx1 = 1.6;       ly1 = 0.7;         a1 = -0.785
lx2 = -2.373776; ly2 = 1.027135;   a2 = 0.785
lx3 = -2.373776; ly3 = -1.027135;  a3 = -0.785
lx4 = 1.6;       ly4 = -0.7;        a4 = 0.785

In [75]:
tau = np.array([[0],[200],[0]])

T = np.array([[np.cos(a1),np.cos(a2),np.cos(a3),np.cos(a4)],
              [np.sin(a1),np.sin(a2),np.sin(a3),np.sin(a4)],
              [lx1*np.sin(a1) - ly1*np.cos(a1), lx2*np.sin(a2) - ly2*np.cos(a2), lx3*np.sin(a3) - ly3*np.cos(a3), lx4*np.sin(a4) - ly4*np.cos(a4)]])

T[:,1] = np.zeros(3) 
T[:,2] = np.zeros(3)
T

array([[ 0.70738827,  0.        ,  0.        ,  0.70738827],
       [-0.70682518,  0.        ,  0.        ,  0.70682518],
       [-1.62609208,  0.        ,  0.        ,  1.62609208]])

In [76]:
T_pinv = np.linalg.pinv(T)
f = np.dot(T_pinv,tau)
f[2][0]

0.0

In [65]:
T_pinv

array([[ 0.70682541, -0.11241655, -0.25862075],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70682541,  0.11241655,  0.25862075]])

In [66]:
l1=2 ;l2=3; l3=4

In [67]:
for i in range(np.shape(T)[1]):
    print(i)

0
1
2
3


In [68]:
f = inverse_glf_map(f)

In [69]:
f

array([[-0.55826529],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]])

In [70]:
len(T)

3

In [77]:
f

array([[-22.48330964],
       [  0.        ],
       [  0.        ],
       [ 22.48330964]])

In [78]:
inverse_glf_map(f[0])

-0.5582652862574011

In [82]:
inverse_glf_map(f[3])

0.02317730416926815

In [1]:
def ssa(angle):
    return angle if angle < 180 else angle-360

In [4]:
ssa(340)

-20